locales = [ "fr",]
[[paths]]
reference = "templates/pages/home/youth/internet-safety/do-you-know-the-person-adding-you.pot"
l10n = "locales/{locale}/pages/home/youth/internet-safety/do-you-know-the-person-adding-you.po"
locales = [ "fr",]

[[paths]]
reference = "templates/pages/home/youth.pot"
l10n = "locales/{locale}/pages/home/youth.po"
locales = [ "fr",]

[[paths]]
reference = "templates/pages/home/youth/internet-safety.pot"
l10n = "locales/{locale}/pages/home/youth/internet-safety.po"
locales = [ "fr",]

